---
- name: K8s 离线部署初始化 (适配本地 v3.26.1 镜像)tets
  hosts: all
  gather_facts: yes
  vars:
    k8s_ver: "1.28.2-0"
    # 严格匹配你脚本拉取的版本
    calico_ver: "v3.26.1"

  tasks:
    # --- 1. 环境彻底清理 ---
    - name: 1.1 物理清理残留 (防止旧网络插件冲突)
      shell: |
        kubeadm reset -f || true
        # 强制清理 Go 程序可能产生的 tigera-operator 残留
        /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf delete ns tigera-operator calico-system --timeout=10s || true
        rm -rf /etc/kubernetes/ /var/lib/kubelet/ /var/lib/etcd/ /etc/cni/net.d/* /opt/cni/bin/*
      ignore_errors: yes

    - name: 1.2 对齐系统时间
      shell: "ntpdate ntp.aliyun.com || date -s '2025-12-29 11:15:00'"
      ignore_errors: yes

    - name: 1.3 内核环境准备
      shell: |
        systemctl stop firewalld && systemctl disable firewalld
        setenforce 0 && sed -i 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
        swapoff -a && sed -i '/swap/s/^/#/' /etc/fstab
        modprobe overlay && modprobe br_netfilter
        cat <<EOF | tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF
        sysctl --system

    # --- 2. 容器运行时配置 (确保 SystemdCgroup 开启) ---
    - name: 2.1 写入 Containerd 配置文件
      copy:
        dest: /etc/containerd/config.toml
        content: |
          version = 2
          [plugins."io.containerd.grpc.v1.cri"]
            sandbox_image = "registry.aliyuncs.com/google_containers/pause:3.9"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true

    - name: 2.2 重启 Containerd 服务
      shell: |
        sed -i 's|^ExecStart=.*|ExecStart=/usr/bin/containerd --config /etc/containerd/config.toml|g' /usr/lib/systemd/system/containerd.service
        systemctl daemon-reload && systemctl restart containerd

    # --- 3. K8s 组件安装 ---
    - name: 3.1 配置 YUM 并安装核心组件
      shell: |
        cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
        enabled=1
        gpgcheck=0
        EOF
        yum install -y kubelet-{{ k8s_ver }} kubeadm-{{ k8s_ver }} kubectl-{{ k8s_ver }}
        systemctl enable --now kubelet

    # --- 4. 准备离线 Calico 配置文件 ---
    - name: 4.1 分发本地 calico.yaml 到 Master
      copy:
        src: "./resources/calico.yaml"
        dest: "/tmp/calico.yaml"
        mode: '0644'
      when: inventory_hostname in groups['master']

    - name: 4.2 修正 Calico 配置以匹配离线环境
      shell: |
        # 1. 强制将版本号改为 v3.26.1 (匹配你离线导入的镜像)
        sed -i 's/v3.26.[0-9]/v3.26.1/g' /tmp/calico.yaml
        
        # 2. 修正 Pod 网段 (必须与 Go 代码中的 10.244.0.0/16 匹配)
        sed -i 's/192.168.0.0\/16/10.244.0.0\/16/g' /tmp/calico.yaml
        
        # 3. 确保镜像路径中包含 docker.io (匹配你的 docker pull 脚本)
        # 如果你的 YAML 已经是 docker.io/calico/... 则无需此行
        # sed -i 's/image: calico\//image: docker.io\/calico\//g' /tmp/calico.yaml
      when: inventory_hostname in groups['master']

    - name: 5.1 部署成功提示
      debug:
        msg: "基础环境准备就绪，离线 Calico 配置文件已在 /tmp/calico.yaml 生成。"